pipelines:
  - name: "Export_rents_to_csv"
    search:
      query:
        country: 'es'
        operation: 'sale'
        propertyType: 'homes'
        locale: 'es'
      geoQuery:
        city: 'Madrid'
        distance: 5000
      filters:
        minSize: 30
        minPrice: 100000
        maxPrice: 280000
        sinceDate: 'W'
      limit: 50
    store:
      type: "tsv"
      output: "./output/sales.tsv"

  - name: "Export_sales_to_csv"
    search:
      query:
        country: 'es'
        operation: 'rent'
        propertyType: 'homes'
        locale: 'es'
      geoQuery:
        city: 'Madrid'
        distance: 5000
      filters:
        minSize: 30
        minPrice: 400
        maxPrice: 1500
        sinceDate: 'W'
      limit: 50
    store :
      type: "tsv"
      output: "./output/rents.tsv"