pipelines:
  - name: "Export_sales_to_csv"
    search:
      query:
        country: 'es'
        operation: 'sale'
        propertyType: 'homes'
        locale: 'es'
      geoQuery:
        city: 'Madrid'
        distance: 7500
      filters:
        minSize: 30
        minPrice: 100000
        maxPrice: 280000
        sinceDate: 'Y'
      limit: 50
    store:
      type: "tsv"
      output: "../output/sales"

  - name: "Export_rents_to_csv"
    search:
      query:
        country: 'es'
        operation: 'rent'
        propertyType: 'homes'
        locale: 'es'
      geoQuery:
        city: 'Madrid'
        distance: 7500
      filters:
        minSize: 30
        minPrice: 400
        maxPrice: 1500
        sinceDate: 'T'
      limit: 50
    store:
      type: "tsv"
      output: "../output/rents"
  - name: "Join_sales_csv"
    run:
      function: "join_csv"
      arg: "../output/sales"
  - name: "Join_rents_csv"
    run:
      function: "join_csv"
      arg: "../output/rents"