[tool.poetry]
name = "idealista"
version = "0.1.0"
description = ""
authors = ["angelpuertadiaz@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0"
pandas = "^2.0.0"


[build-system]
requires = ["poetry-core", "request", "logging", "csv", "dacite"]
build-backend = "poetry.core.masonry.api"
